In [1]:
import numpy as np
import pandas as pd

In [2]:
# Load raw data
df = pd.read_table("data/RN2_Pix.dat", sep="\s+", names=["subject", "session", "list", "recog_pos", "picture", "category", "study_pos", "old_lag", "study_lag", "confidence", "rt"])
df

,subject,session,list,recog_pos,picture,category,study_pos,old_lag,study_lag,confidence,rt
0,103,1,0,1,VA084,_OLD_,6,-999,59,6,705
1,103,1,0,2,GBEN253,_OLD_,5,-1,61,6,936
2,103,1,0,3,ONTO011,_OLD_,3,-2,64,6,678
3,103,1,0,4,ISBO1,_NEW_,-99,-999,-9999,4,1461
4,103,1,0,5,PAGETT11,_OLD_,38,-999,31,5,1799
...,...,...,...,...,...,...,...,...,...,...,...
69883,99,1,5,124,CHN639,_NEW_,-99,-999,-9999,4,1460
69884,99,1,5,125,CT173,_OLD_,39,-999,150,2,1040
69885,99,1,5,126,GRTO2,_NEW_,-99,-999,-9999,2,1269
69886,99,1,5,127,GR022,_OLD_,46,-999,145,1,887
69887,99,1,5,128,VNDPGCC,_OLD_,44,-2,148,2,1154

In [3]:
# Check the number of subjects
df["subject"].unique().shape

(91,)

In [4]:
# Get rid of invalid trials where rt < 50 or rt > 3000 (also get rid of rt == 0 and confidence == 0)
df = df.query("50 <= rt <= 3000").copy()
df

,subject,session,list,recog_pos,picture,category,study_pos,old_lag,study_lag,confidence,rt
0,103,1,0,1,VA084,_OLD_,6,-999,59,6,705
1,103,1,0,2,GBEN253,_OLD_,5,-1,61,6,936
2,103,1,0,3,ONTO011,_OLD_,3,-2,64,6,678
3,103,1,0,4,ISBO1,_NEW_,-99,-999,-9999,4,1461
4,103,1,0,5,PAGETT11,_OLD_,38,-999,31,5,1799
...,...,...,...,...,...,...,...,...,...,...,...
69883,99,1,5,124,CHN639,_NEW_,-99,-999,-9999,4,1460
69884,99,1,5,125,CT173,_OLD_,39,-999,150,2,1040
69885,99,1,5,126,GRTO2,_NEW_,-99,-999,-9999,2,1269
69886,99,1,5,127,GR022,_OLD_,46,-999,145,1,887
69887,99,1,5,128,VNDPGCC,_OLD_,44,-2,148,2,1154

In [6]:
# Binarize old/new
df["old"] = df.category == "_OLD_"
df

,subject,session,list,recog_pos,picture,category,study_pos,old_lag,study_lag,confidence,rt,old
0,103,1,0,1,VA084,_OLD_,6,-999,59,6,705,True
1,103,1,0,2,GBEN253,_OLD_,5,-1,61,6,936,True
2,103,1,0,3,ONTO011,_OLD_,3,-2,64,6,678,True
3,103,1,0,4,ISBO1,_NEW_,-99,-999,-9999,4,1461,False
4,103,1,0,5,PAGETT11,_OLD_,38,-999,31,5,1799,True
...,...,...,...,...,...,...,...,...,...,...,...,...
69883,99,1,5,124,CHN639,_NEW_,-99,-999,-9999,4,1460,False
69884,99,1,5,125,CT173,_OLD_,39,-999,150,2,1040,True
69885,99,1,5,126,GRTO2,_NEW_,-99,-999,-9999,2,1269,False
69886,99,1,5,127,GR022,_OLD_,46,-999,145,1,887,True
69887,99,1,5,128,VNDPGCC,_OLD_,44,-2,148,2,1154,True

In [7]:
# Save
df.to_parquet("data/simu2_Schwartz_preproc.parquet")