In [208]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import CMR_IA as cmr
import sys

sys.path.append("../../Modeling/fitting")
from optimization_utils import make_boundary
from object_funcs import anal_perform_6b as anal_perform

In [209]:
SAVERES = False

## Load Stimuli and Semantic Matrix

In [210]:
with open("simu6b_data/simu6b_design.pkl", "rb") as inp:
    df_study = pickle.load(inp)
    df_test = pickle.load(inp)
df_study = df_study.loc[df_study.session < 100]  # for testing
df_test = df_test.loc[df_test.session < 100]

In [211]:
df_study

      study_itemno1  study_itemno2 study_item1 study_item2  list  session
0               120            459        BELT      DIAPER     0        0
1              1315           1260      SKETCH     SEAFOOD     0        0
2               357            723   COMPANION     HOSTESS     0        0
3              1551           1202        VEAL      ROCKET     0        0
4              1081           1066       PLANE     PIGMENT     0        0
...             ...            ...         ...         ...   ...      ...
7195           1019           1143     PASSAGE       PUPIL     5       99
7196            293           1375      CHERRY       STEAM     5       99
7197            871            927      MARKET       MOVIE     5       99
7198           1392           1486      STREAM    TORTOISE     5       99
7199            305            986      CHISEL       OTTER     5       99

[7200 rows x 6 columns]

In [212]:
df_test

,test_itemno1,test_itemno2,test_item,correct_ans,order,rep,test,list,session,test_pos,pair_idx
0,51,-1,ASTRONAUT,1083,2,1,1,0,0,1,8
1,1202,-1,ROCKET,1551,2,1,1,0,0,2,4
2,979,-1,OPERATOR,142,1,1,1,0,0,3,11
3,134,-1,BLADE,105,1,1,1,0,0,4,9
4,1081,-1,PLANE,1066,1,1,1,0,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
14395,1019,-1,PASSAGE,1143,1,1,2,5,99,20,7196
14396,487,-1,DOORBELL,788,2,1,2,5,99,21,7189
14397,723,-1,HOSTESS,1378,2,1,2,5,99,22,7192
14398,196,-1,BULLY,786,1,1,2,5,99,23,7190
14399,293,-1,CHERRY,1375,1,1,2,5,99,24,7197

In [213]:
s_mat = np.load("../wordpools/ltp_FR_similarity_matrix.npy")

## Run CMR-IA

In [214]:
# define parameters
params = cmr.make_default_params()
params.update(learn_while_retrieving=False, nitems_in_accumulator=96, use_new_context=True)

In [215]:
# load pso results
_, _, what_to_fit = make_boundary(sim_name="6b")
optim_params = np.loadtxt("simu6b_data/6b_250408_200-200.txt")
for pname, pvalue in zip(what_to_fit, optim_params):
    params[pname] = pvalue
params.update(beta_enc_inpair=0.05)  # learn_while_retrieving=False
params

{'beta_enc': 0.866662,
 'beta_rec': 0.550292,
 'beta_cue': 0.971412,
 'beta_rec_post': 0.082552,
 'beta_distract': 0.480264,
 'beta_enc_inpair': 0.05,
 'phi_s': 3.254107,
 'phi_d': 0.477546,
 's_cf': 0.367439,
 's_fc': 0.255119,
 'kappa': 0.188473,
 'eta': 0.001319,
 'omega': 6.681985,
 'alpha': 0.790381,
 'lamb': 0.103443,
 'c_thresh': 0.451522,
 'c_thresh_itm': 0.5,
 'c_thresh_assoc': 0.5,
 'd_assoc': 0,
 'rec_time_limit': 60000.0,
 'dt': 10,
 'nitems_in_accumulator': 96,
 'max_recalls': 50,
 'learn_while_retrieving': False,
 'use_new_context': True,
 'use_flexible_thresh': False,
 'psi_s': 0,
 'psi_c': 1,
 'c_s': 0,
 'thresh_sigma': 0,
 'ban_recall': None,
 'var_enc': 1,
 'bad_enc_ratio': 1,
 'recog_slope': 1,
 'gamma_fc': 0.360799,
 'gamma_cf': 0.345657}

In [216]:
# run the model
df_simu, f_in, f_dif = cmr.run_success_multi_sess(params, df_study, df_test, s_mat, mode="CR-CR")
# df_simu["test_pos"] = np.tile(np.arange(1, 25), 6000)
df_simu["test_pos"] = np.tile(np.arange(1, 25), 600)

# merge to get more info
df_simu = df_simu.merge(df_test, on=["session", "list", "test_itemno1", "test_itemno2", "test_pos"])
df_simu["correct"] = df_simu.s_resp == df_simu.correct_ans
df_simu

  0%|          | 0/100 [00:00<?, ?it/s]

100%|██████████| 100/100 [00:45<00:00,  2.21it/s]

CMR Time: 45.291598081588745

,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct
0,0,0,51,-1,-1.0,-1.0,-1.000000,1,ASTRONAUT,1083,2,1,1,8,False
1,0,0,1202,-1,1551.0,3030.0,0.522379,2,ROCKET,1551,2,1,1,4,True
2,0,0,979,-1,-1.0,-1.0,-1.000000,3,OPERATOR,142,1,1,1,11,False
3,0,0,134,-1,-1.0,-1.0,-1.000000,4,BLADE,105,1,1,1,9,False
4,0,0,1081,-1,12.0,3870.0,0.535872,5,PLANE,1066,1,1,1,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14395,99,5,1019,-1,-1.0,-1.0,-1.000000,20,PASSAGE,1143,1,1,2,7196,False
14396,99,5,487,-1,788.0,1600.0,0.520041,21,DOORBELL,788,2,1,2,7189,True
14397,99,5,723,-1,-1.0,-1.0,-1.000000,22,HOSTESS,1378,2,1,2,7192,False
14398,99,5,196,-1,786.0,1380.0,0.583908,23,BULLY,786,1,1,2,7190,True
14399,99,5,293,-1,-2.0,-2.0,0.318662,24,CHERRY,1375,1,1,2,7197,False

In [217]:
# get condition and congruence
df_cond = df_simu.groupby(["pair_idx", "test"])["order"].mean().to_frame(name="corr_rate").reset_index()
df_cond = df_cond.pivot_table(index="pair_idx", columns="test", values="corr_rate").reset_index()
df_cond.columns = ["pair_idx", "test1", "test2"]


def cond(x):
    test1 = x["test1"]
    test2 = x["test2"]
    if test1 == 1 and test2 == 1:
        return "F-F"
    elif test1 == 1 and test2 == 2:
        return "F-B"
    elif test1 == 2 and test2 == 1:
        return "B-F"
    elif test1 == 2 and test2 == 2:
        return "B-B"


df_cond["cond"] = df_cond.apply(lambda x: cond(x), axis=1)
df_cond["cong"] = df_cond.apply(lambda x: "Identical" if x["cond"] == "F-F" or x["cond"] == "B-B" else "Reversed", axis=1)
df_cond

      pair_idx  test1  test2 cond       cong
0            1    1.0    1.0  F-F  Identical
1            2    2.0    1.0  B-F   Reversed
2            3    1.0    1.0  F-F  Identical
3            4    2.0    1.0  B-F   Reversed
4            5    1.0    2.0  F-B   Reversed
...        ...    ...    ...  ...        ...
7195      7196    2.0    1.0  B-F   Reversed
7196      7197    1.0    1.0  F-F  Identical
7197      7198    2.0    1.0  B-F   Reversed
7198      7199    1.0    2.0  F-B   Reversed
7199      7200    2.0    2.0  B-B  Identical

[7200 rows x 5 columns]

In [218]:
# merge condition and congruence
pairidx2cond = df_cond.loc[:, ["pair_idx", "cond"]].set_index("pair_idx").to_dict()["cond"]
pairidx2cong = df_cond.loc[:, ["pair_idx", "cong"]].set_index("pair_idx").to_dict()["cong"]
df_simu["cond"] = df_simu.apply(lambda x: pairidx2cond[x["pair_idx"]], axis=1)
df_simu["cong"] = df_simu.apply(lambda x: pairidx2cong[x["pair_idx"]], axis=1)
df_simu.head(24)

,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct,cond,cong
0,0,0,51,-1,-1.0,-1.0,-1.000000,1,ASTRONAUT,1083,2,1,1,8,False,B-B,Identical
1,0,0,1202,-1,1551.0,3030.0,0.522379,2,ROCKET,1551,2,1,1,4,True,B-F,Reversed
2,0,0,979,-1,-1.0,-1.0,-1.000000,3,OPERATOR,142,1,1,1,11,False,F-F,Identical
3,0,0,134,-1,-1.0,-1.0,-1.000000,4,BLADE,105,1,1,1,9,False,F-B,Reversed
4,0,0,1081,-1,12.0,3870.0,0.535872,5,PLANE,1066,1,1,1,5,False,F-B,Reversed
5,0,0,357,-1,723.0,1660.0,0.587411,6,COMPANION,723,1,1,1,3,True,F-F,Identical
6,0,0,831,-1,-1.0,-1.0,-1.000000,7,LITERATURE,1435,2,1,1,7,False,B-B,Identical
7,0,0,1188,-1,-1.0,-1.0,-1.000000,8,RIB,641,2,1,1,12,False,B-F,Reversed
8,0,0,1260,-1,1315.0,2440.0,0.495662,9,SEAFOOD,1315,2,1,1,2,True,B-F,Reversed
9,0,0,12,-1,-1.0,-1.0,-1.000000,10,AIRPLANE,226,1,1,1,10,False,F-B,Reversed
10,0,0,546,-1,-1.0,-1.0,-1.000000,11,EYELASH,1087,2,1,1,6,False,B-B,Identical
11,0,0,120,-1,459.0,860.0,0.559110,12,BELT,459,1,1,1,1,True,F-F,Identical
12,0,0,51,-1,-1.0,-1.0,-1.000000,13,ASTRONAUT,1083,2,1,2,8,False,B-B,Identical
13,0,0,120,-1,459.0,860.0,0.559141,14,BELT,459,1,1,2,1,True,F-F,Identical
14,0,0,641,-1,-1.0,-1.0,-1.000000,15,GLOBE,1188,1,1,2,12,False,B-F,Reversed
15,0,0,1066,-1,-1.0,-1.0,-1.000000,16,PIGMENT,1081,2,1,2,5,False,F-B,Reversed
16,0,0,831,-1,1435.0,4490.0,0.520106,17,LITERATURE,1435,2,1,2,7,True,B-B,Identical
17,0,0,1551,-1,1202.0,3600.0,0.530298,18,VEAL,1202,1,1,2,4,True,B-F,Reversed
18,0,0,105,-1,-1.0,-1.0,-1.000000,19,BEAN,134,2,1,2,9,False,F-B,Reversed
19,0,0,357,-1,723.0,1530.0,0.584831,20,COMPANION,723,1,1,2,3,True,F-F,Identical
20,0,0,1315,-1,1260.0,1300.0,0.501779,21,SKETCH,1260,1,1,2,2,True,B-F,Reversed
21,0,0,979,-1,-1.0,-1.0,-1.000000,22,OPERATOR,142,1,1,2,11,False,F-F,Identical
22,0,0,226,-1,12.0,3770.0,0.565777,23,CANAL,12,2,1,2,10,True,F-B,Reversed
23,0,0,546,-1,-1.0,-1.0,-1.000000,24,EYELASH,1087,2,1,2,6,False,B-B,Identical

In [219]:
# get f_in
sessions = np.unique(df_simu.session.to_numpy())
tmp_corr_fin = []
tmp_omean_fin = []
tmp_omax_fin = []

for sess in sessions:
    df_tmp = df_study.loc[df_study.session == sess]
    tmp1 = df_tmp.study_itemno1.to_numpy()
    tmp2 = df_tmp.study_itemno2.to_numpy()
    tmp = np.concatenate((tmp1, tmp2))
    tmp = np.sort(tmp)

    df_tmp1 = df_simu.loc[df_simu.session == sess]
    tmp_test = df_tmp1.test_itemno1
    tmp_corr = df_tmp1.correct_ans
    # tmp_test = df_simu.loc[df_simu.session == sess, 'test_itemno']
    # tmp_corr = df_simu.loc[df_simu.session == sess, 'correct_ans']
    testid = np.searchsorted(tmp, tmp_test)
    corrid = np.searchsorted(tmp, tmp_corr)

    fin_sess = f_dif[sess]
    # tmp_corr_fin = []
    # tmp_omean_fin = []
    # tmp_omax_fin = []
    for i in range(len(testid)):
        tmp_corr_fin.append(fin_sess[i][corrid[i]])
        tmp_omean_fin.append(np.mean(np.delete(fin_sess[i], corrid[i])))
        tmp_omax_fin.append(np.delete(fin_sess[i], corrid[i]).max())
    # df_simu.loc[df_simu.session == sess, 'corr_fin']= tmp_corr_fin
    # df_simu.loc[df_simu.session == sess, 'omean_fin'] = tmp_omean_fin
    # df_simu.loc[df_simu.session == sess, 'omax_fin'] = tmp_omax_fin

df_simu["corr_fin"] = tmp_corr_fin
df_simu["omean_fin"] = tmp_omean_fin
df_simu["omax_fin"] = tmp_omax_fin
df_simu

,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct,cond,cong,corr_fin,omean_fin,omax_fin
0,0,0,51,-1,-1.0,-1.0,-1.000000,1,ASTRONAUT,1083,2,1,1,8,False,B-B,Identical,-0.405694,-0.833482,-0.546860
1,0,0,1202,-1,1551.0,3030.0,0.522379,2,ROCKET,1551,2,1,1,4,True,B-F,Reversed,-0.249198,-0.875270,-0.474359
2,0,0,979,-1,-1.0,-1.0,-1.000000,3,OPERATOR,142,1,1,1,11,False,F-F,Identical,-0.616804,-1.031146,-0.655247
3,0,0,134,-1,-1.0,-1.0,-1.000000,4,BLADE,105,1,1,1,9,False,F-B,Reversed,-0.390922,-0.986374,-0.487936
4,0,0,1081,-1,12.0,3870.0,0.535872,5,PLANE,1066,1,1,1,5,False,F-B,Reversed,-0.384794,-1.047561,-0.308906
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14395,99,5,1019,-1,-1.0,-1.0,-1.000000,20,PASSAGE,1143,1,1,2,7196,False,B-F,Reversed,-0.553291,-1.114922,-0.583641
14396,99,5,487,-1,788.0,1600.0,0.520041,21,DOORBELL,788,2,1,2,7189,True,B-B,Identical,0.214443,-0.964121,-0.206100
14397,99,5,723,-1,-1.0,-1.0,-1.000000,22,HOSTESS,1378,2,1,2,7192,False,F-B,Reversed,-0.278042,-1.038586,-0.302123
14398,99,5,196,-1,786.0,1380.0,0.583908,23,BULLY,786,1,1,2,7190,True,F-F,Identical,0.249928,-1.102903,-0.401473
14399,99,5,293,-1,-2.0,-2.0,0.318662,24,CHERRY,1375,1,1,2,7197,False,F-F,Identical,-0.474087,-1.112045,-0.201528

In [220]:
df_fin = df_simu.groupby(["cong", "test"])[["corr_fin", "omean_fin", "omax_fin"]].mean().reset_index()
df_fin["dif"] = df_fin["corr_fin"] - df_fin["omax_fin"]
df_fin

        cong  test  corr_fin  omean_fin  omax_fin       dif
0  Identical     1 -0.264359  -0.996366 -0.322048  0.057688
1  Identical     2 -0.263912  -0.995125 -0.319682  0.055770
2   Reversed     1 -0.270103  -0.996100 -0.321826  0.051723
3   Reversed     2 -0.267878  -0.995890 -0.321313  0.053435

In [221]:
if SAVERES:
    df_simu.to_pickle("simu6b_data/simu6b_result.pkl")

## Analysis

In [222]:
# with open("simu6b_data/simu6b_result.pkl", "rb") as inp:
#     df_simu = pickle.load(inp)

In [223]:
# anal_perform used by pso
subjects = np.unique(df_simu.session)
inde_stats = []
reve_stats = []
for subj in subjects:
    df_subj_inde = df_simu.query(f"session == {subj} and cong == 'Identical'").copy()
    inde_stats.append(list(anal_perform(df_subj_inde)))

    df_subj_reve = df_simu.query(f"session == {subj} and cong == 'Reversed'").copy()
    reve_stats.append(list(anal_perform(df_subj_reve)))

In [224]:
np.array(inde_stats)

array([[0.33333333, 0.        , 0.05555556, 0.61111111, 0.99115044],
       [0.25      , 0.02777778, 0.02777778, 0.69444444, 0.98159509],
       [0.27777778, 0.        , 0.        , 0.72222222, 0.99820467],
       [0.27777778, 0.02777778, 0.        , 0.69444444, 0.99441341],
       [0.36111111, 0.02777778, 0.05555556, 0.55555556, 0.97326203],
       [0.30555556, 0.        , 0.        , 0.69444444, 0.99829642],
       [0.25      , 0.        , 0.        , 0.75      , 0.99808795],
       [0.19444444, 0.        , 0.02777778, 0.77777778, 0.99300699],
       [0.22222222, 0.02777778, 0.02777778, 0.72222222, 0.98021978],
       [0.30555556, 0.02777778, 0.        , 0.66666667, 0.99469027],
       [0.30555556, 0.        , 0.08333333, 0.61111111, 0.9865643 ],
       [0.25      , 0.        , 0.05555556, 0.69444444, 0.98973306],
       [0.19444444, 0.05555556, 0.02777778, 0.72222222, 0.96296296],
       [0.25      , 0.        , 0.05555556, 0.69444444, 0.98973306],
       [0.36111111, 0.        , 0.02777778, 0.61111111, 0.99507389],
       [0.25      , 0.        , 0.02777778, 0.72222222, 0.99405941],
       [0.16666667, 0.        , 0.08333333, 0.75      , 0.98060942],
       [0.25      , 0.02777778, 0.05555556, 0.66666667, 0.96828753],
       [0.30555556, 0.02777778, 0.02777778, 0.63888889, 0.98348624],
       [0.36111111, 0.02777778, 0.05555556, 0.55555556, 0.97326203],
       [0.36111111, 0.        , 0.02777778, 0.61111111, 0.99507389],
       [0.25      , 0.        , 0.        , 0.75      , 0.99808795],
       [0.25      , 0.02777778, 0.02777778, 0.69444444, 0.98159509],
       [0.30555556, 0.02777778, 0.02777778, 0.63888889, 0.98348624],
       [0.25      , 0.        , 0.        , 0.75      , 0.99808795],
       [0.27777778, 0.        , 0.02777778, 0.69444444, 0.99441341],
       [0.30555556, 0.        , 0.        , 0.69444444, 0.99829642],
       [0.25      , 0.        , 0.        , 0.75      , 0.99808795],
       [0.27777778, 0.        , 0.        , 0.72222222, 0.99820467],
       [0.25      , 0.        , 0.        , 0.75      , 0.99808795],
       [0.30555556, 0.02777778, 0.02777778, 0.63888889, 0.98348624],
       [0.25      , 0.02777778, 0.05555556, 0.66666667, 0.96828753],
       [0.38888889, 0.02777778, 0.        , 0.58333333, 0.9952    ],
       [0.33333333, 0.        , 0.        , 0.66666667, 0.99836868],
       [0.30555556, 0.        , 0.02777778, 0.66666667, 0.99469027],
       [0.33333333, 0.02777778, 0.08333333, 0.55555556, 0.95984704],
       [0.16666667, 0.02777778, 0.        , 0.80555556, 0.99220779],
       [0.33333333, 0.        , 0.        , 0.66666667, 0.99836868],
       [0.30555556, 0.        , 0.02777778, 0.66666667, 0.99469027],
       [0.19444444, 0.        , 0.05555556, 0.75      , 0.98795181],
       [0.33333333, 0.        , 0.02777778, 0.63888889, 0.99490662],
       [0.38888889, 0.        , 0.05555556, 0.55555556, 0.99162479],
       [0.36111111, 0.02777778, 0.        , 0.61111111, 0.99507389],
       [0.30555556, 0.08333333, 0.02777778, 0.58333333, 0.95841584],
       [0.22222222, 0.05555556, 0.        , 0.72222222, 0.98896247],
       [0.33333333, 0.        , 0.        , 0.66666667, 0.99836868],
       [0.30555556, 0.05555556, 0.        , 0.63888889, 0.9907919 ],
       [0.25      , 0.        , 0.        , 0.75      , 0.99808795],
       [0.30555556, 0.        , 0.        , 0.69444444, 0.99829642],
       [0.25      , 0.02777778, 0.        , 0.72222222, 0.99405941],
       [0.22222222, 0.08333333, 0.02777778, 0.66666667, 0.95081967],
       [0.19444444, 0.05555556, 0.02777778, 0.72222222, 0.96296296],
       [0.38888889, 0.        , 0.02777778, 0.58333333, 0.9952    ],
       [0.38888889, 0.        , 0.        , 0.61111111, 0.99846861],
       [0.25      , 0.02777778, 0.        , 0.72222222, 0.99405941],
       [0.25      , 0.02777778, 0.        , 0.72222222, 0.99405941],
       [0.27777778, 0.        , 0.        , 0.72222222, 0.99820467],
       [0.30555556, 0.05555556, 0.02777778, 0.61111111, 0.97142857],
       [0.19444444, 0.02777778, 0.05555556, 0.72222222, 0.96296296],
       [0.22222222, 0.02777778, 0.02777778, 0.72222222, 0.98021978],
       [0.30555556, 0.02777778, 0.02777778, 0.63888889, 0.98348624],
       [0.19444444, 0.        , 0.02777778, 0.77777778, 0.99300699],
       [0.19444444, 0.02777778, 0.        , 0.77777778, 0.99300699],
       [0.27777778, 0.        , 0.        , 0.72222222, 0.99820467],
       [0.33333333, 0.02777778, 0.        , 0.63888889, 0.99490662],
       [0.38888889, 0.        , 0.        , 0.61111111, 0.99846861],
       [0.30555556, 0.        , 0.        , 0.69444444, 0.99829642],
       [0.30555556, 0.        , 0.        , 0.69444444, 0.99829642],
       [0.30555556, 0.        , 0.05555556, 0.63888889, 0.9907919 ],
       [0.27777778, 0.        , 0.08333333, 0.63888889, 0.98591549],
       [0.22222222, 0.        , 0.02777778, 0.75      , 0.99360341],
       [0.30555556, 0.        , 0.02777778, 0.66666667, 0.99469027],
       [0.25      , 0.02777778, 0.05555556, 0.66666667, 0.96828753],
       [0.22222222, 0.        , 0.02777778, 0.75      , 0.99360341],
       [0.19444444, 0.02777778, 0.        , 0.77777778, 0.99300699],
       [0.30555556, 0.        , 0.11111111, 0.58333333, 0.98196393],
       [0.19444444, 0.        , 0.        , 0.80555556, 0.99774266],
       [0.27777778, 0.02777778, 0.05555556, 0.63888889, 0.97005988],
       [0.22222222, 0.        , 0.02777778, 0.75      , 0.99360341],
       [0.36111111, 0.02777778, 0.        , 0.61111111, 0.99507389],
       [0.19444444, 0.        , 0.05555556, 0.75      , 0.98795181],
       [0.27777778, 0.02777778, 0.        , 0.69444444, 0.99441341],
       [0.27777778, 0.05555556, 0.        , 0.66666667, 0.99032882],
       [0.25      , 0.02777778, 0.02777778, 0.69444444, 0.98159509],
       [0.25      , 0.02777778, 0.02777778, 0.69444444, 0.98159509],
       [0.36111111, 0.02777778, 0.        , 0.61111111, 0.99507389],
       [0.27777778, 0.        , 0.        , 0.72222222, 0.99820467],
       [0.22222222, 0.        , 0.02777778, 0.75      , 0.99360341],
       [0.30555556, 0.05555556, 0.05555556, 0.58333333, 0.95069034],
       [0.30555556, 0.        , 0.02777778, 0.66666667, 0.99469027],
       [0.22222222, 0.05555556, 0.08333333, 0.63888889, 0.91606715],
       [0.25      , 0.        , 0.02777778, 0.72222222, 0.99405941],
       [0.30555556, 0.05555556, 0.02777778, 0.61111111, 0.97142857],
       [0.30555556, 0.05555556, 0.02777778, 0.61111111, 0.97142857],
       [0.22222222, 0.02777778, 0.        , 0.75      , 0.99360341],
       [0.19444444, 0.        , 0.02777778, 0.77777778, 0.99300699],
       [0.22222222, 0.02777778, 0.        , 0.75      , 0.99360341],
       [0.27777778, 0.        , 0.        , 0.72222222, 0.99820467],
       [0.33333333, 0.05555556, 0.        , 0.61111111, 0.99115044],
       [0.44444444, 0.02777778, 0.05555556, 0.47222222, 0.97435897]])

In [225]:
np.array(reve_stats)

array([[0.25      , 0.05555556, 0.05555556, 0.63888889, 0.94553377],
       [0.33333333, 0.05555556, 0.02777778, 0.58333333, 0.97247706],
       [0.16666667, 0.13888889, 0.11111111, 0.58333333, 0.69908815],
       [0.22222222, 0.08333333, 0.11111111, 0.58333333, 0.84130982],
       [0.19444444, 0.08333333, 0.05555556, 0.66666667, 0.90909091],
       [0.22222222, 0.08333333, 0.11111111, 0.58333333, 0.84130982],
       [0.33333333, 0.05555556, 0.02777778, 0.58333333, 0.97247706],
       [0.27777778, 0.08333333, 0.11111111, 0.52777778, 0.85714286],
       [0.22222222, 0.08333333, 0.05555556, 0.63888889, 0.91606715],
       [0.19444444, 0.        , 0.05555556, 0.75      , 0.98795181],
       [0.16666667, 0.13888889, 0.05555556, 0.63888889, 0.83483483],
       [0.27777778, 0.08333333, 0.        , 0.63888889, 0.98591549],
       [0.27777778, 0.16666667, 0.11111111, 0.44444444, 0.71111111],
       [0.08333333, 0.13888889, 0.11111111, 0.66666667, 0.5520362 ],
       [0.16666667, 0.08333333, 0.08333333, 0.66666667, 0.85714286],
       [0.25      , 0.11111111, 0.08333333, 0.55555556, 0.85035629],
       [0.36111111, 0.        , 0.08333333, 0.55555556, 0.98743268],
       [0.25      , 0.08333333, 0.05555556, 0.61111111, 0.92134831],
       [0.19444444, 0.        , 0.11111111, 0.69444444, 0.97674419],
       [0.22222222, 0.02777778, 0.05555556, 0.69444444, 0.96598639],
       [0.22222222, 0.08333333, 0.08333333, 0.61111111, 0.87960688],
       [0.33333333, 0.08333333, 0.05555556, 0.52777778, 0.93069307],
       [0.30555556, 0.05555556, 0.08333333, 0.55555556, 0.92842536],
       [0.27777778, 0.02777778, 0.11111111, 0.58333333, 0.94193548],
       [0.16666667, 0.05555556, 0.22222222, 0.55555556, 0.72491909],
       [0.25      , 0.02777778, 0.16666667, 0.55555556, 0.90464548],
       [0.25      , 0.16666667, 0.08333333, 0.5       , 0.77078086],
       [0.27777778, 0.        , 0.05555556, 0.66666667, 0.99032882],
       [0.25      , 0.08333333, 0.05555556, 0.61111111, 0.92134831],
       [0.19444444, 0.08333333, 0.08333333, 0.63888889, 0.87002653],
       [0.25      , 0.05555556, 0.08333333, 0.61111111, 0.92134831],
       [0.08333333, 0.19444444, 0.02777778, 0.69444444, 0.7761194 ],
       [0.16666667, 0.08333333, 0.08333333, 0.66666667, 0.85714286],
       [0.27777778, 0.        , 0.08333333, 0.63888889, 0.98591549],
       [0.30555556, 0.05555556, 0.05555556, 0.58333333, 0.95069034],
       [0.19444444, 0.02777778, 0.05555556, 0.72222222, 0.96296296],
       [0.19444444, 0.16666667, 0.05555556, 0.58333333, 0.81690141],
       [0.25      , 0.11111111, 0.05555556, 0.58333333, 0.89559165],
       [0.33333333, 0.        , 0.11111111, 0.55555556, 0.98259188],
       [0.30555556, 0.05555556, 0.11111111, 0.52777778, 0.9044586 ],
       [0.13888889, 0.08333333, 0.05555556, 0.72222222, 0.88673139],
       [0.16666667, 0.02777778, 0.05555556, 0.75      , 0.95890411],
       [0.19444444, 0.05555556, 0.08333333, 0.66666667, 0.90909091],
       [0.16666667, 0.02777778, 0.22222222, 0.58333333, 0.83278689],
       [0.33333333, 0.02777778, 0.05555556, 0.58333333, 0.97247706],
       [0.22222222, 0.05555556, 0.11111111, 0.61111111, 0.88888889],
       [0.19444444, 0.08333333, 0.08333333, 0.63888889, 0.87002653],
       [0.25      , 0.13888889, 0.05555556, 0.55555556, 0.86810552],
       [0.22222222, 0.08333333, 0.05555556, 0.63888889, 0.91606715],
       [0.27777778, 0.05555556, 0.05555556, 0.61111111, 0.94845361],
       [0.30555556, 0.05555556, 0.05555556, 0.58333333, 0.95069034],
       [0.16666667, 0.02777778, 0.08333333, 0.72222222, 0.94084507],
       [0.30555556, 0.05555556, 0.05555556, 0.58333333, 0.95069034],
       [0.25      , 0.08333333, 0.08333333, 0.58333333, 0.88683603],
       [0.27777778, 0.13888889, 0.11111111, 0.47222222, 0.76258993],
       [0.33333333, 0.11111111, 0.08333333, 0.47222222, 0.86567164],
       [0.25      , 0.02777778, 0.13888889, 0.58333333, 0.92235294],
       [0.25      , 0.02777778, 0.        , 0.72222222, 0.99405941],
       [0.30555556, 0.        , 0.08333333, 0.61111111, 0.9865643 ],
       [0.19444444, 0.02777778, 0.13888889, 0.63888889, 0.91056911],
       [0.30555556, 0.08333333, 0.02777778, 0.58333333, 0.95841584],
       [0.30555556, 0.05555556, 0.        , 0.63888889, 0.9907919 ],
       [0.25      , 0.11111111, 0.02777778, 0.61111111, 0.93877551],
       [0.19444444, 0.11111111, 0.05555556, 0.63888889, 0.88      ],
       [0.25      , 0.08333333, 0.08333333, 0.58333333, 0.88683603],
       [0.16666667, 0.16666667, 0.08333333, 0.58333333, 0.72      ],
       [0.19444444, 0.11111111, 0.13888889, 0.55555556, 0.72268908],
       [0.25      , 0.08333333, 0.02777778, 0.63888889, 0.95404814],
       [0.13888889, 0.16666667, 0.08333333, 0.61111111, 0.6894198 ],
       [0.22222222, 0.08333333, 0.11111111, 0.58333333, 0.84130982],
       [0.38888889, 0.02777778, 0.02777778, 0.55555556, 0.98497496],
       [0.13888889, 0.05555556, 0.08333333, 0.72222222, 0.88673139],
       [0.02777778, 0.13888889, 0.11111111, 0.72222222, 0.23255814],
       [0.25      , 0.05555556, 0.08333333, 0.61111111, 0.92134831],
       [0.38888889, 0.05555556, 0.02777778, 0.52777778, 0.97382199],
       [0.25      , 0.11111111, 0.08333333, 0.55555556, 0.85035629],
       [0.30555556, 0.08333333, 0.05555556, 0.55555556, 0.92842536],
       [0.19444444, 0.08333333, 0.02777778, 0.69444444, 0.94656489],
       [0.30555556, 0.05555556, 0.13888889, 0.5       , 0.8785872 ],
       [0.11111111, 0.16666667, 0.        , 0.72222222, 0.94693878],
       [0.36111111, 0.        , 0.11111111, 0.52777778, 0.98305085],
       [0.27777778, 0.13888889, 0.02777778, 0.55555556, 0.9261745 ],
       [0.16666667, 0.11111111, 0.08333333, 0.63888889, 0.81305638],
       [0.22222222, 0.        , 0.05555556, 0.72222222, 0.98896247],
       [0.27777778, 0.11111111, 0.08333333, 0.52777778, 0.85714286],
       [0.13888889, 0.05555556, 0.05555556, 0.75      , 0.92063492],
       [0.22222222, 0.02777778, 0.05555556, 0.69444444, 0.96598639],
       [0.22222222, 0.02777778, 0.02777778, 0.72222222, 0.98021978],
       [0.13888889, 0.        , 0.13888889, 0.72222222, 0.96296296],
       [0.25      , 0.02777778, 0.11111111, 0.61111111, 0.93877551],
       [0.25      , 0.05555556, 0.08333333, 0.61111111, 0.92134831],
       [0.27777778, 0.02777778, 0.08333333, 0.61111111, 0.95652174],
       [0.16666667, 0.        , 0.11111111, 0.72222222, 0.97421203],
       [0.27777778, 0.02777778, 0.08333333, 0.61111111, 0.95652174],
       [0.25      , 0.02777778, 0.05555556, 0.66666667, 0.96828753],
       [0.25      , 0.08333333, 0.11111111, 0.55555556, 0.85035629],
       [0.16666667, 0.05555556, 0.13888889, 0.63888889, 0.83483483],
       [0.30555556, 0.02777778, 0.13888889, 0.52777778, 0.92903226],
       [0.25      , 0.02777778, 0.11111111, 0.61111111, 0.93877551],
       [0.11111111, 0.        , 0.02777778, 0.86111111, 0.98947368]])

In [226]:
np.mean(inde_stats, axis=0)

array([0.27861111, 0.0175    , 0.02388889, 0.68      , 0.98741267])

In [227]:
np.mean(reve_stats, axis=0)

array([0.23583333, 0.06888889, 0.07833333, 0.61694444, 0.89513115])

In [228]:
inde_stats_mean = np.mean(inde_stats, axis=0)
reve_stats_mean = np.mean(reve_stats, axis=0)
inde_ground_truth = np.array([0.319, 0.006, 0.012, 0.663, 0.94])
reve_ground_truth = np.array([0.293, 0.049, 0.122, 0.537, 0.96])
err = (np.mean(np.power(inde_stats_mean - inde_ground_truth, 2)) + np.mean(np.power(reve_stats_mean - reve_ground_truth, 2))) / 2
err

0.002061127502649901